apiVersion: kafka.strimzi.io/v1
kind: KafkaTopic
metadata:
  name: cdc-public-order-items
  namespace: streaming
  labels:
    strimzi.io/cluster: kafka-dev
spec:
  topicName: debezium.public.order_items
  partitions: 3
  replicas: 1
  config:
    cleanup.policy: compact,delete
    compression.type: snappy
    retention.ms: "604800000"
    delete.retention.ms: "86400000"
    min.compaction.lag.ms: "0"
    segment.bytes: "67108864"
    min.insync.replicas: "1"
