apiVersion: v1
kind: Service
metadata:
  name: trino
  namespace: lakehouse
  labels:
    app: trino
    app.kubernetes.io/part-of: real-time-lakehouse
    layer: storage-query
spec:
  type: ClusterIP
  selector:
    app: trino
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      protocol: TCP
